version: '3.7'

services:

  api:
    build:
      context: ./src
      dockerfile: Dockerfile
      args:
        app_name: ${COMPOSE_PROJECT_NAME}
    command: uvicorn app.main:api --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src:/usr/src
    # ports:
    # - 8000:8000
    network_mode: host
    environment:
      - ENVIRONMENT=dev
      - TESTING=0

